version: '3.8'

services:
  backend:
    build: ./
    working_dir: /usr/src/app
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - .:/usr/src/app:cached
      - rust_cargo:/usr/local/cargo/registry
      - rust_target:/usr/src/app/target
    command: tail -f /dev/null

volumes:
  rust_target:
  rust_cargo:
